### PR TITLE
New feature

### PR DESCRIPTION
**Pull request by marcoM32**
Added a feature to view online the license of this app and point out the free nature of this project

### CODE REVIEW

**Comment by billthefarmer** [comment]
I have tested this. I think it is better to make the licence item in the About dialog a link to the GNU GPL file. The extra preference item looks odd with two horizontal lines round it.

**Comment by marcoM32** [comment]
Some changes to the previous integration

**Comment by billthefarmer** [comment]
You've got a merge marker in [AboutPreference.java](https://github.com/billthefarmer/diary/pull/30/commits/efccbed17d315923ed00901b088ad80bdc0c1f63#diff-dc227b6afe553145aaecef19fd8ed1b0) because I have already made the changes as part of the next release which I haven't finished testing yet.

**Comment by marcoM32** [comment]
Excuse me, now I fixed the problem.

**Comment by billthefarmer** [comment]
I will incorporate this into the next version, but not merge it here because of merge conflicts

**Comment by marcoM32** [comment]
OK no problem! This request can then be closed

**Pull request closed without merging**
