### PR TITLE
Update README.md - add repository map link

### PR DESCRIPTION
**Pull request by alexkarezin**
Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/billthefarmerdiary/). Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.

In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.

### CODE REVIEW

**Comment by billthefarmer** [comment]
I don't think this is particularly useful because...
It's an app, not a library
I don't put Javadoc comments in my apps.

**Comment by alexkarezin** [comment]
Thank you Bill! My intent was to make it easier for new contributors to understand the code base. Do you think it would be useful for that? Is there anything I can do to make it better? I'd really appreciate any feedback!

**Comment by alexkarezin** [comment]
> I'd really appreciate any feedback!
@billthefarmer 
Bill, if it's not too much to ask any chance we can chat? I'd be really curious how you view a good project structure visualization. Thx!

**Comment by billthefarmer** [comment]
I have looked at your web site, it appears to be in the F-Droid anti-feature category 'Non-Free Network Services'. The example you give for OSMDroid appears to be a good use case, which I don't think applies to this app.

**Pull request closed without merging**
